In [5]:
import sys
sys.path.append("../helper_functions")
import duneapi_utils as d
import growthepieapi_utils as gtp
sys.path.pop()

# Usage
merged_df = gtp.get_growthepie_api_data()
merged_df = merged_df.reset_index()
display(merged_df.sample(5))

Failed to retrieve data for stables. HTTP Status code: 403

,index,date,chain_name,daa,txcount,txcosts_usd,txcosts_eth,tvl_usd,tvl_eth,fees_usd,fees_eth
1365,1365,2022-06-09,Optimism,17241.0,90115.0,0.552071,0.000308,8.370272e+08,4.664301e+05,6.858603e+04,38.219288
2327,2327,2022-10-13,Arbitrum One,28878.0,216325.0,0.080500,0.000062,2.386343e+09,1.843774e+06,2.259149e+04,17.454991
4011,4011,2021-08-02,Optimism,NaN,NaN,NaN,NaN,8.250724e+07,3.228731e+04,NaN,NaN
3098,3098,2022-06-15,Immutable X,11176.0,941149.0,NaN,NaN,4.580862e+07,3.770672e+04,8.747752e+02,0.720059
1026,1026,2023-05-05,Polygon zkEVM,464.0,1869.0,1.512075,0.000805,5.286001e+06,2.815595e+03,5.925055e+03,3.155988
728,728,2022-12-30,Ethereum,314236.0,944771.0,1.105358,0.000920,NaN,NaN,2.546999e+06,2119.773106
1663,1663,2023-04-03,Optimism,49898.0,260033.0,0.257811,0.000143,1.928526e+09,1.072752e+06,9.375826e+04,52.153494
532,532,2022-06-17,Ethereum,370636.0,1110579.0,1.739662,0.001628,NaN,NaN,4.285551e+06,4010.421999
1289,1289,2022-03-25,Optimism,2543.0,40510.0,0.894377,0.000288,5.840188e+08,1.879895e+05,4.848963e+04,15.608299
1889,1889,2021-08-01,Arbitrum One,15.0,4447.0,0.646351,0.000254,4.337391e+05,1.706509e+02,3.024009e+03,1.189770

In [ ]:
# Post to Dune API
d.write_dune_api_from_pandas(merged_df, 'growthepie_l2_activity',\
                             'L2 Usage Activity from GrowThePie')